### ISSUE TITLE
MMF

### ISSUE THREAD

**Issue by jacob2461** [nekosune/modularforcefieldsystem#61]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  craftfallessentials (CraftfallEssentials-1.12.2-1.2.1.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.7.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/29/19 2:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Modular ForceField System (modularforcefieldsystem)
Caused by: java.lang.NoClassDefFoundError: com/nekokittygames/mffs/common/guide/LightGuideBook
	at com.nekokittygames.mffs.common.ModularForceFieldSystem.preInit(ModularForceFieldSystem.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.nekokittygames.mffs.common.guide.LightGuideBook
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: amerifrance/guideapi/api/IGuideBook
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: amerifrance.guideapi.api.IGuideBook
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 827400552 bytes (789 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version      | Source                               | Signature                                |
	|:----- |:----------------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft               | 1.12.2       | minecraft.jar                        | None                                     |
	| LCH   | mcp                     | 9.42         | minecraft.jar                        | None                                     |
	| LCH   | FML                     | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                   | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ftblib                  | 5.4.3.132    | FTBLib-5.4.3.132.jar                 | None                                     |
	| LCH   | ftbutilities            | 5.4.0.102    | FTBUtilities-5.4.0.102.jar           | None                                     |
	| LCH   | lucraftcore             | 1.12.2-2.4.7 | LucraftCore-1.12.2-2.4.7.jar         | None                                     |
	| LCH   | heroesexpansion         | 1.12.2-1.3.5 | HeroesExpansion-1.12.2-1.3.5.jar     | None                                     |
	| LCH   | craftfallessentials     | 1.2.1        | CraftfallEssentials-1.12.2-1.2.1.jar | None                                     |
	| LCH   | mca                     | 6.0.0        | MCA-1.12.2-6.0.0-universal.jar       | None                                     |
	| LCE   | modularforcefieldsystem | 3.0.1        | MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar | None                                     |
	| LC    | radixcore               | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| LC    | star-tech               | 1.1.1        | star-tech-1.1.1.jar                  | None                                     |

	Loaded coremods (and transformers): 
craftfallessentials (CraftfallEssentials-1.12.2-1.2.1.jar)
  com.hydrosimp.craftfallessentials.core.CEClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.7.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'

**Comment by Chocohead** [comment]
Duplicate of #30, #35, #39 and #40, you need to get [Guide-API](https://minecraft.curseforge.com/projects/guide-api) and [Redstone Flux](https://minecraft.curseforge.com/projects/redstone-flux) too.
