### ISSUE TITLE
Undeclared dependency on IC2

### ISSUE THREAD

**Issue by Baughn** [nekosune/modularforcefieldsystem#7]
As you can see in https://travis-ci.org/TPPIC/Test-Factory-Please-Ignore/builds/185780260, MMFS crashes on startup if IC2Exp isn't installed, but there's no declared dependency on IC2 in the Curse build.

Since there also aren't any instructions to install it, and the output refers to an "IC2 module", I suspect this is a bug in the code rather than a missing dependency.

```
[14:15:57] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[14:15:57] [Server thread/ERROR] [FML]: Caught exception from Modular ForceField System (modularforcefieldsystem)
java.lang.NoClassDefFoundError: ic2/api/tile/ExplosionWhitelist
	at com.nekokittygames.mffs.common.MFFSMaschines.initialize(MFFSMaschines.java:137) ~[MFFSMaschines.class:?]
	at com.nekokittygames.mffs.common.ModularForceFieldSystem.load(ModularForceFieldSystem.java:591) ~[ModularForceFieldSystem.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_122]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_122]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_122]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_122]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_122]

(...)
```

**Comment by GaeaKat** [comment]
This is fixed already, there will be a released build in the near future, want to finish the new guide
